name: Android Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'gradle'
        
    - name: Validate and fix gradlew
      run: |
        echo "=== Avant correction ==="
        ls -la gradlew || echo "gradlew non trouvé"
        
        # Forcer le téléchargement si manquant ou corrompu
        if [ ! -f "gradlew" ] || ! grep -q "gradle" gradlew; then
          echo "Téléchargement d'un nouveau gradlew..."
          curl -L https://raw.githubusercontent.com/gradle/gradle/master/gradlew -o gradlew
        fi
        
        # Donner les permissions
        chmod +x gradlew
        
        echo "=== Après correction ==="
        ls -la gradlew
        file gradlew
        
        # Vérifier le contenu
        head -5 gradlew
        
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      
    - name: Build with Gradle
      run: |
        # Essayer d'abord avec le wrapper
        ./gradlew tasks --no-daemon || echo "Gradle wrapper failed, trying system gradle..."
        
        # Si le wrapper échoue, utiliser gradle système
        gradle build --no-daemon || ./gradlew build --no-daemon
        
    - name: Upload APK
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: okitakoyvpn-apk
        path: app/build/outputs/apk/
        
