name: Ultimate Build

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Create new gradlew
      run: |
        # Supprimer l'ancien gradlew problématique
        rm -f gradlew
        
        # Créer un nouveau gradlew simple mais fonctionnel
        cat > gradlew << 'SCRIPT'
#!/bin/bash
# Simple gradlew wrapper
java -jar gradle/wrapper/gradle-wrapper.jar "$@"
SCRIPT
        
        chmod +x gradlew
        ls -la gradlew
        
    - name: Download gradle wrapper jar
      run: |
        mkdir -p gradle/wrapper
        curl -L -o gradle/wrapper/gradle-wrapper.jar \
          https://repo.maven.apache.org/maven2/org/grade/gradle-wrapper/7.5.1/gradle-wrapper-7.5.1.jar || \
        curl -L -o gradle/wrapper/gradle-wrapper.jar \
          https://github.com/gradle/gradle/raw/master/gradle/wrapper/gradle-wrapper.jar || \
        echo "Will use system gradle"
        
    - name: Build with fallback
      run: |
        # Essayer le wrapper d'abord
        if [ -f "gradlew" ] && [ -x "gradlew" ]; then
          echo "Using gradlew wrapper"
          ./gradlew build || gradle build
        else
          echo "Using system gradle"
          gradle build
        fi
        
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-output
        path: |
          app/build/outputs/apk/
          app/build/reports/
